#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    MoveStoryLeft,
    MoveStoryRight,
    OpenDetail,
    CloseDetail,
    NewStory,
    NewTask,
    DeleteStory,
    DeleteTask,
    ToggleTask,
    EditStoryTitle,
    OpenEpicList,
    ConfirmYes,
    ConfirmNo,
    InputChar(char),
    InputBackspace,
    InputConfirm,
    InputCancel,
}
